Reduce the appliance disk size if possible

diff --git a/templates/steps/export/save_appliance_from_nbd.yaml b/templates/steps/export/save_appliance_from_nbd.yaml
--- a/templates/steps/export/save_appliance_from_nbd.yaml
+++ b/templates/steps/export/save_appliance_from_nbd.yaml
@@ -36,19 +36,33 @@
   - exec_out: echo "Saved raw appliance to $(pwd)/$$filename.raw"
 
 - save_as_qcow2:
+  - exec_in: |
+      dd if=/dev/zero of=/bigemptyfile bs=1M 2>&1 >/dev/null || true
+  - exec_in: rm -f /bigemptyfile
   - exec_out: echo "sync..." ; sync
   - exec_out: |
-      qemu-img convert -O qcow2 $(readlink $$container) $$filename.qcow2
+      qemu-img convert -c -O qcow2 $(readlink $$container) $$filename.qcow2
   - exec_out: echo "Saved qcow2 appliance to $(pwd)/$$filename.qcow2"
 
 - save_as_vmdk:
+  - exec_in: |
+      dd if=/dev/zero of=/bigemptyfile bs=1M 2>&1 >/dev/null || true
+  - exec_in: rm -f /bigemptyfile
   - exec_out: echo "sync..." ; sync
   - exec_out: |
       qemu-img convert -O vmdk $(readlink $$container) $$filename.vmdk
   - exec_out: echo "Saved vmdk appliance to $(pwd)/$$filename.vmdk"
 
 - save_as_vdi:
+  - exec_in: |
+      dd if=/dev/zero of=/bigemptyfile bs=1M 2>&1 >/dev/null || true
+  - exec_in: rm -f /bigemptyfile
   - exec_out: echo "sync..." ; sync
-  - exec_out: |
-      qemu-img convert -O vdi $(readlink $$container) $$filename.vdi
+  - exec_out: qemu-img convert -O vdi $(readlink $$container) $$filename.vdi
+  - rescue:
+    - exec_out: |
+        echo "Compact the vdi disk"
+        VBoxManage modifyhd $$filename.vdi --compact 2>&1
+    - exec_out: |
+        echo "Cannot compact the vdi disk : VBoxManage is missing."
   - exec_out: echo "Saved vdi appliance to $(pwd)/$$filename.vdi"
